<?php
// Copy this file to config.php after running install/install.php.
// Values will be generated by the installer.
return [
    'app' => [
        'name' => 'SMM Panel',
        'base_url' => '', // e.g. https://yourdomain.com
        'timezone' => 'UTC',
        'currency' => 'USD',
        'global_markup_percent' => 0.0, // Applied on top of provider rate
    ],
    'db' => [
        'host' => 'localhost',
        'name' => 'smm_panel',
        'user' => 'db_user',
        'pass' => 'db_pass',
        'charset' => 'utf8mb4',
    ],
    'security' => [
        'session_name' => 'smm_session',
        'cookie_lifetime' => 86400 * 7, // 7 days
    ],
    'payments' => [
        'paypal' => [
            'enabled' => false,
            'business_email' => '', // Your PayPal business email
            'currency' => 'USD',    // Must match PayPal currency in your account
            'ipn_verify_url' => 'https://ipnpb.paypal.com/cgi-bin/webscr', // Live IPN
            // For sandbox testing:
            // 'ipn_verify_url' => 'https://ipnpb.sandbox.paypal.com/cgi-bin/webscr',
        ],
    ],
    // Optional email settings for forgot-password delivery
    'mail' => [
        'enabled' => false,
        'from' => 'no-reply@yourdomain.com',
    ],
];